### ISSUE TITLE
Error: Kind not found

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/azure-databricks-operator#168]
When I run `make` commands I this error: `/usr/local/bin/kind: 1: /usr/local/bin/kind: Not: not found `

I'm also unable to create a kind cluster to deploy to

**Comment by Fryguy** [comment]
For future people coming to this issue or one like it... "Not: not found" happens when `curl` retrieves a 404 specifically from GitHub releases (and perhaps similarly with other locations).  It will write "Not Found" in binary to the file, but not exit with a failing exit code.  Instead, one can do `curl -f` to force a failing exit code.

Typically, people will code something that is roughly

```shell
curl -o /usr/local/bin/foo https://example.com/foo
chmod +x /usr/local/bin/foo
/usr/local/bin/foo --version
```

When the shell tries to run that "Not Found" file, it will see the first line as "Not found" and attempt to execute that line, however "Not" isn't a valid executable, leading to the lovely error:

    /usr/local/bin/foo: 1: /usr/local/bin/foo: Not: not found
